seeds = [1000]
iterations = 1
gpu = 1
timeout_seconds = 900
log_interval = 1
timing_mode = "none"

[[designs]]
name = "superblue1_ot_notiming"
base_config = "../dreamplace_base/iccad2015_notiming/superblue1_ot_notiming.json"
timing_mode = "none"
