# ICCAD2015 Superblue DREAMPlace-only search panel.
# Timing is disabled because local HeteroSTA timing requires a license.

seeds = [1000]
iterations = 30
gpu = 1
timeout_seconds = 3600
log_interval = 10
timing_mode = "none"

[[designs]]
name = "superblue1_ot_notiming"
dreamplace_config = "../dreamplace_base/iccad2015_notiming/superblue1_ot_notiming.json"
timing_mode = "none"

[[designs]]
name = "superblue3_ot_notiming"
dreamplace_config = "../dreamplace_base/iccad2015_notiming/superblue3_ot_notiming.json"
timing_mode = "none"
